export {default as Home} from './Home'
export {default as SignUp} from './SignUp'
export {default as SignIn} from './SignIn'
export {default as Wordbooks} from './Wordbooks'
export {default as TakeTest} from './TakeTest'